version: '3.8'

services:
  # Trac service with proper initialization
  trac:
    image: python:2.7
    container_name: trac-aws
    working_dir: /trac
    environment:
      - TRAC_PROJECT=learntrac
      - PYTHONPATH=/trac/plugins
      - TRAC_INI_PATH=/trac/conf/trac.ini
    ports:
      - "8000:8000"
    volumes:
      - ./docker/init-trac-simple.sh:/init-trac.sh:ro
      - ./conf/trac.ini:/trac/conf/trac.ini
      - ./plugins:/trac/plugins
      - ./htdocs:/trac/htdocs
      - ./templates:/trac/templates
      - trac-data:/trac/data
    env_file:
      - .env.aws
    command: /init-trac.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - learntrac-network
  
  # Learning API service with better error handling
  learning-api:
    image: python:3.11-slim
    container_name: learning-api
    working_dir: /app
    ports:
      - "8001:8001"
    volumes:
      - ./learntrac-api/src:/app/src
      - ./learntrac-api/requirements-minimal.txt:/app/requirements.txt:ro
    env_file:
      - .env.aws
    networks:
      - learntrac-network
    command: >
      bash -c "
        set -eo pipefail &&
        echo 'Installing dependencies...' &&
        apt-get update -qq && apt-get install -y -qq gcc libpq-dev curl &&
        pip install --quiet --no-cache-dir -r /app/requirements.txt &&
        echo 'Starting Learning API...' &&
        cd /app &&
        python src/minimal_api.py"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  trac-data:

networks:
  learntrac-network:
    driver: bridge