version: '3.8'

services:
  learning-api:
    build:
      context: ./learntrac-api
      dockerfile: Dockerfile
    container_name: learntrac-api
    environment:
      # Database configuration
      - DATABASE_URL=postgresql://learntrac_admin:learntrac_password@host.docker.internal:5432/learntrac
      
      # Neo4j configuration
      - NEO4J_URI=bolt://host.docker.internal:7687
      - NEO4J_USER=neo4j
      - NEO4J_USERNAME=neo4j  # Both vars for compatibility
      - NEO4J_PASSWORD=8pQcA75CGQYcUNaZTHKYZSAo8tO9h-Z5oqkxk_G1c1o
      
      # Redis configuration
      - REDIS_URL=redis://host.docker.internal:6379
      
      # OpenAI configuration (dummy for now)
      - OPENAI_API_KEY=sk-dummy-key
      - OPENAI_MODEL=gpt-4
      
      # Application configuration
      - LOG_LEVEL=INFO
      - ENVIRONMENT=development
    ports:
      - "8001:8001"
    volumes:
      - ./learntrac-api/src:/app/src
      - ./learntrac-api/scripts/start-api-simple.sh:/app/scripts/start-api-simple.sh
    command: ["/bin/bash", "/app/scripts/start-api-simple.sh"]
    extra_hosts:
      - "host.docker.internal:host-gateway"