version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: learntrac-postgres
    environment:
      - POSTGRES_DB=learntrac
      - POSTGRES_USER=learntrac_admin
      - POSTGRES_PASSWORD=learntrac_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./learntrac-infrastructure/database/init:/docker-entrypoint-initdb.d
    networks:
      - learntrac-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U learntrac_admin -d learntrac"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Trac Service
  trac:
    image: learntrac-trac:test
    container_name: learntrac-trac
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://learntrac_admin:learntrac_password@postgres:5432/learntrac
      - TRAC_ENV=/var/trac/projects/learntrac
    ports:
      - "8000:8000"
    volumes:
      - trac-data:/var/trac/projects
      - ./plugins/learntrac_display:/app/plugins/learntrac_display
    networks:
      - learntrac-network

  # Learning Service API
  api:
    image: learntrac/api:test
    container_name: learntrac-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://learntrac_admin:learntrac_password@postgres:5432/learntrac
      - DB_USER=learntrac_admin
      - DB_PASSWORD=learntrac_password
      - RDS_ENDPOINT=postgres:5432
      - DB_NAME=learntrac
      - COGNITO_USER_POOL_ID=test-pool
      - COGNITO_CLIENT_ID=test-client
      - COGNITO_DOMAIN=test-domain
      - AWS_REGION=us-east-2
    ports:
      - "8001:8001"
    networks:
      - learntrac-network
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

networks:
  learntrac-network:
    driver: bridge

volumes:
  postgres-data:
  trac-data: