# Development override configuration
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  trac:
    build:
      context: ./docker/trac
      dockerfile: Dockerfile
    environment:
      - TRAC_DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      # Mount source code for hot reloading
      - ./docker/trac/plugins:/app/plugins:ro
      - ./docker/trac/templates:/app/templates:ro
      - ./docker/trac/config:/app/config:ro
      # Mount logs as writable
      - ./logs/trac:/var/log/trac:rw
    command: >
      bash -c "pip install --editable /app/plugins/learntrac_display &&
               pip install --editable /app/plugins/learningpathmacro &&
               /usr/local/bin/start-trac.sh"

  learning-service:
    build:
      context: ./learntrac-api
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=DEBUG
      - RELOAD=true
    volumes:
      # Mount source code for hot reloading
      - ./learntrac-api/src:/app/src:ro
      - ./learntrac-api/alembic:/app/alembic:ro
      - ./learntrac-api/scripts:/app/scripts:ro
      # Mount logs as writable
      - ./logs/api:/var/log/api:rw
    command: >
      bash -c "pip install --editable . &&
               uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload --log-level debug"

  # Enable Neo4j for local development
  neo4j-dev:
    profiles: []  # Always enabled in dev

  # Enable Redis for local development
  redis-dev:
    profiles: []  # Always enabled in dev